### ISSUE TITLE
Fixture files need to be created for the install process and the initial admin user

### ISSUE THREAD

**Issue by trystant** [trystant/drywall#6]
The current install process includes creating an admin user in the database and then going through the "forgot password" section in order to create the first user. There should be an easier way to start things up. One piece of that includes creating a fixture file(s) in order to handle that request. The following code

``` javascript
db.admingroups.insert({ _id: 'root', name: 'Root' });
db.admins.insert({ name: {first: 'Root', last: 'Admin', full: 'Root Admin'}, groups: ['root'] });
var rootAdmin = db.admins.findOne();
db.users.save({ username: 'root', isActive: 'yes', email: 'your@email.addy', roles: {admin: rootAdmin._id} });
var rootUser = db.users.findOne();
rootAdmin.user = { id: rootUser._id, name: rootUser.username };
db.admins.save(rootAdmin);
```

needs to be turned into a JSON fixture used by [sequelize-fixtures](https://github.com/domasx2/sequelize-fixtures)

**Comment by trystant** [comment]
I've been working on this task, and have run into an error when running the `database/load_initial_data.js` program as follows:

`> node database/load_initial_data.js`

This resulted in the following error:

```
Unhandled rejection TypeError: Cannot read property 'id' of null
    at null.<anonymous> (/Users/mnyon/code/drywall/node_modules/sequelize-fixtures/lib/loader.js:118:55)
    at tryCatcher (/Users/mnyon/code/drywall/node_modules/sequelize/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/mnyon/code/drywall/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:489:31)
    at Promise._settlePromiseAt (/Users/mnyon/code/drywall/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:565:18)
    at Async._drainQueue (/Users/mnyon/code/drywall/node_modules/sequelize/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/mnyon/code/drywall/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mnyon/code/drywall/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

I'm assuming that it has something to do with using property names as opposed to IDs. Research needs to be done in that direction.

**Comment by trystant** [comment]
Looking at this further, it seems that the error is happening upon user creation, likely in relation to the fixture format.

**Comment by trystant** [comment]
I ran into several challenges while trying to get this fixture file to work:

First, there was a json error relating to the Sequelize.JSON data type in the schema. The error was:

```
Executing (default): SELECT "id", "name", "permissions", "createdAt", "updatedAt" FROM "AdminGroup" AS "AdminGroup" WHERE "AdminGroup"."name" = 'root' AND "AdminGroup"."permissions" = '' LIMIT 1;
ERROR: SequelizeDatabaseError: operator does not exist: json = unknown
    at Query.formatError (/Users/mnyon/code/drywall/node_modules/sequelize/lib/dialects/postgres/query.js:423:14)
    at null.<anonymous> (/Users/mnyon/code/drywall/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
    at emit (events.js:107:17)
    at Query.handleError (/Users/mnyon/code/drywall/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/Users/mnyon/code/drywall/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/Users/mnyon/code/drywall/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

At one point I updated Postgres from 9.3 to 9.4 (which is a completely different ticket). Once that was done, the JSON error persisted. My solution for that was to change the JSON types to STRING in the form of [Sequelize Migrations](https://sequelize.readthedocs.org/en/latest/docs/migrations/). Once those were run, I ran into the following error:

```
Fixtures: reading file fixtures/initial_seed.json...
Executing (default): SELECT "id", "name", "permissions", "createdAt", "updatedAt" FROM "AdminGroup" AS "AdminGroup" WHERE "AdminGroup"."name" = 'root' AND "AdminGroup"."permissions" = '' LIMIT 1;
attribute "User' not defined on  model 'Admin'.
Executing (default): SELECT "id", "name", "permissions", "createdAt", "updatedAt" FROM "AdminGroup" AS "AdminGroup" WHERE "AdminGroup"."name" = 'root' LIMIT 1;
Executing (default): SELECT "id", "name", "userId", "createdAt", "updatedAt", "AdminGroupId" FROM "Admin" AS "Admin" WHERE "Admin"."name" = 'Root Admin' AND "Admin"."AdminGroupId" = 7 LIMIT 1;
Executing (default): SELECT "id", "username", "password", "email", "isActive", "resetPasswordToken", "resetPasswordExpires", "twitter", "github", "facebook", "google", "tumblr", "createdAt", "updatedAt", "AdminId" FROM "User" AS "User" WHERE "User"."username" = 'root' AND "User"."email" = 'mark@grandkru.com' AND "User"."isActive" = 'yes' LIMIT 1;
ERROR: SequelizeDatabaseError: column "AdminId" does not exist
    at Query.formatError (/Users/mnyon/code/drywall/node_modules/sequelize/lib/dialects/postgres/query.js:423:14)
    at null.<anonymous> (/Users/mnyon/code/drywall/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
    at emit (events.js:107:17)
    at Query.handleError (/Users/mnyon/code/drywall/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/Users/mnyon/code/drywall/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/Users/mnyon/code/drywall/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

At this point, there's an error in how the models are relating to each other. Once the relationship model is resolved.

**Comment by trystant** [comment]
Returning to this issue a month later, it looks like

`> node database/load_initial_data.js`

results in the following error:

```
mnyon@mnyon ~/code/drywall (git::6_sequelize_fixture_wip) ] node database/load_initial_data.js
DEBUG: 1
DEBUG: 2
DEBUG: 3
DEBUG: 4
DEBUG: Before loadFile
DEBUG: After loadFile
Fixtures: reading file fixtures/initial_seed.json...
Executing (default): SELECT "id", "name", "permissions", "createdAt", "updatedAt" FROM "AdminGroup" AS "AdminGroup" WHERE "AdminGroup"."name" = 'root' AND "AdminGroup"."permissions" = '' LIMIT 1;
attribute "User' not defined on  model 'Admin'.
Executing (default): SELECT "id", "name", "permissions", "createdAt", "updatedAt" FROM "AdminGroup" AS "AdminGroup" WHERE "AdminGroup"."name" = 'root' LIMIT 1;
Executing (default): SELECT "id", "name", "userId", "createdAt", "updatedAt", "AdminGroupId" FROM "Admin" AS "Admin" WHERE "Admin"."name" = 'Root Admin' AND "Admin"."AdminGroupId" = 7 LIMIT 1;
Executing (default): SELECT "id", "username", "password", "email", "isActive", "resetPasswordToken", "resetPasswordExpires", "twitter", "github", "facebook", "google", "tumblr", "createdAt", "updatedAt", "AdminId" FROM "User" AS "User" WHERE "User"."username" = 'root' AND "User"."email" = 'mark@grandkru.com' AND "User"."isActive" = 'yes' LIMIT 1;
ERROR: SequelizeDatabaseError: column "AdminId" does not exist
    at Query.formatError (/Users/mnyon/code/drywall/node_modules/sequelize/lib/dialects/postgres/query.js:423:14)
    at null.<anonymous> (/Users/mnyon/code/drywall/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
    at emit (events.js:107:17)
    at Query.handleError (/Users/mnyon/code/drywall/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/Users/mnyon/code/drywall/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/Users/mnyon/code/drywall/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

Double checking the database
